apiVersion: v1
kind: Pod
metadata:
  name: rootfs-hardened
  namespace: rootfs-lab
spec:
  os:
    name: linux
  automountServiceAccountToken: false
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: demo
      image: busybox:1.37.0
      command: ["sleep", "86400"]
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 100m
          memory: 64Mi
      volumeMounts:
        - name: scratch
          mountPath: /scratch
          bindMountOptions:
            - noexec
            - nosuid
            - nodev
  volumes:
    - name: scratch
      emptyDir:
        sizeLimit: 32Mi
